### PR TITLE
Token Security

### PR DESCRIPTION
**Pull request by Deniernal354**
Hide your tokens using the way I used.

### CODE REVIEW

**Comment by ndr3w221** [comment]
awesome security

**Comment by ndr3w221** [comment]
Btw, this is a test, not a bot, the token is reset'd every time we push the code so dont worry! Feel free to use this method in your bots!

Closed for now, you can reopen if you want

**Comment by boltxyz** [comment]
You need to use [dotenv](https://npmjs.com/package/dotenv) package to use environment variable. Also, use .gitignore to hide the .env. As well as .npmignore to hide while publishing the package.

You can use config file as well. But env seems more better. But the usage are... There is no use if env is pushed with the files as well.

**Comment by gleeny** [comment]
tbh just have the /tests hidden after all and have a new folder called /examples, shoeing **finished and tested examples** and not something WIP. That's the best solution. Also, a dev-branch could be nice if you're pushing frequently without knowing if it's tested.

**Comment by ndr3w221** [comment]
@gleeny here we go!

**Pull request merged**
